backend:
  name: github
  repo: openScouts/zona9.org.ar
  branch: master
  site_domain: zona9

media_folder: static/img
public_folder: /img

collections:
  - name: 'Configuracion'
    label: 'Configuracion'
    files:
      - label: 'Comite'
        name: 'comite'
        file: 'config/comite.json'
        widget: 'list'
        editor:
          preview: false
        fields:
          - label: 'comite'
            name: 'comite'
            widget: 'list'
            summary: '{{fields.funcion}} => {{fields.descripcion}}'
            fields:
              - { name: funcion, label: funcion, widget: string }
              - { name: nombre, label: nombre, widget: string }
              - { name: correo, label: correo, widget: string }
              - { name: descripcion, label: descripcion, widget: markdown }
      - label: 'links'
        name: 'links'
        file: 'config/links.json'
        widget: 'list'
        editor:
          preview: false
        fields:
          - label: 'links'
            name: 'links'
            widget: 'list'
            fields:
              - { name: icono, label: icono, widget: string }
              - { name: titulo, label: titulo, widget: string }
              - { name: descripcion, label: descripcion, widget: string }
              - { name: link, label: link, widget: string }
      - label: 'grupos'
        name: 'grupos'
        file: 'config/grupos.json'
        widget: 'list'
        editor:
          preview: false
        fields:
          - label: 'grupos'
            name: 'grupos'
            widget: 'list'
            fields:
              - { name: id, label: id, widget: string }
              - { name: distrito, label: distrito, widget: string }
              - { name: nombre, label: nombre, widget: string }
              - {
                  name: fundacion,
                  label: fundacion,
                  format: 'D/M/YYYY',
                  widget: date,
                }
              - { name: direccion, label: direccion, widget: string }
              - { name: localidad, label: localidad, widget: string }
              - { name: partido, label: partido, widget: string }
              - { name: Pagina Web, label: Pagina Web, widget: string }
              - { name: Facebook, label: Facebook, widget: string }
              - { name: colores, label: colores, widget: string }
              - { name: Latitud, label: Latitud, widget: string }
              - { name: Longitud, label: Longitud, widget: string }
      - label: 'juventud'
        name: 'juventud'
        file: 'config/juventud.json'
        widget: 'list'
        editor:
          preview: false
        fields:
          - label: 'juventud'
            name: 'juventud'
            widget: 'list'
            summary: '{{fields.titulo}} => {{fields.descripcion}}'
            fields:
              - { name: img, label: img, widget: string }
              - { name: titulo, label: titulo, widget: string }
              - { name: descripcion, label: descripcion, widget: markdown }
              - { name: email, label: email, widget: string }
